# Generated by Django 5.1.7 on 2025-03-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "ISBN",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("Author", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("genre", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("userId", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=255)),
                ("address2", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("zipcode", models.CharField(max_length=10)),
            ],
        ),
    ]
