apiVersion: apps/v1
kind: Deployment
metadata:
  name: book_service
  namespace: bookstore-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book_service
  template:
    metadata:
      labels:
        app: book_service
    spec:
      containers:
      - name: book_service
        image: ygrx532/book_service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /books/status
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
