apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  namespace: bookstore-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
      - name: book-service
        image: ygrx532/book-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /books/status
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 20
