apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: bookstore-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: ygrx532/customer-service:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /customers/status
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 20
