apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer_service
  namespace: bookstore-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer_service
  template:
    metadata:
      labels:
        app: customer_service
    spec:
      containers:
      - name: customer_service
        image: ygrx532/customer_service:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /customers/status
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
