apiVersion: v1
kind: Service
metadata:
  name: customer_service
  namespace: bookstore-ns
spec:
  selector:
    app: customer_service
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
